support role/group/domain meta attributes
AthenZ/terraform-provider-athenz pull request #100
Opened 2023-12-07 22:35 UTC by havetisyan

2023-12-12 23:35 UTC, abvaidya requested changes

2023-12-13 00:07 UTC, havetisyan commented on docker/zms/conf/zms.properties
> +athenz.zms.authority_classes=com.yahoo.athenz.auth.impl.PrincipalAuthority,com.yahoo.athenz.auth.impl.TestUserAuthority,com.yahoo.athenz.auth.impl.PrincipalAuthority,com.yahoo.athenz.auth.impl.TestUs
why not? it's a local file in the repo, it's not coming from the docker image

2023-12-13 01:25 UTC, abvaidya commented on docker/zms/conf/zms.properties
> +athenz.zms.authority_classes=com.yahoo.athenz.auth.impl.PrincipalAuthority,com.yahoo.athenz.auth.impl.TestUserAuthority,com.yahoo.athenz.auth.impl.PrincipalAuthority,com.yahoo.athenz.auth.impl.TestUs
apologies for the confusion. I meant the changes made by makefile to add the authority classes should not be checked in.

2023-12-13 01:28 UTC, abvaidya approved these changes

2023-12-13 01:28 UTC, merged